// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['services']['ConfigService']['GetConfig']();
}

export function WriteConfig(arg1) {
  return window['go']['services']['ConfigService']['WriteConfig'](arg1);
}
