// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function GetConfig():Promise<services.Config>;

export function WriteConfig(arg1:services.Config):Promise<void>;
